name: .NET build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  win64:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet publish --self-contained QuestEyes_Server/QuestEyes_Server.csproj -f net6.0 -o package/win-x64 -c Release -r win-x64 /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Upload build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: QuestEyes_Server.exe (win-x64)
        path: package/win-x64/QuestEyes_Server.exe
        
  win86:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet publish --self-contained QuestEyes_Server/QuestEyes_Server.csproj -f net6.0 -o package/win-x86 -c Release -r win-x86 /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Upload build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: QuestEyes_Server.exe (win-x86)
        path: package/win-x86/QuestEyes_Server.exe
        
  linux:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet publish --self-contained QuestEyes_Server/QuestEyes_Server.csproj -f net6.0 -o package/linux -c Release -r linux-x64 /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Upload build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: QuestEyes_Server (linux-x64)
        path: package/linux/QuestEyes_Server

  macOS:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet publish --self-contained QuestEyes_Server/QuestEyes_Server.csproj -f net6.0 -o package/macos -c Release -r osx-x64 /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Upload build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: QuestEyes_Server (osx-x64)
        path: package/macos
